# Generated by Django 6.1 on 2026-08-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('Sick', 'Sick'), ('Casual', 'Casual'), ('Paid', 'Paid')], default='Casual', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='worklog',
            name='category',
            field=models.CharField(choices=[('Meeting', 'Meeting'), ('Development', 'Development'), ('Bug Fix', 'Bug Fix'), ('Documentation', 'Documentation'), ('Testing', 'Testing'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
