# Generated by Django 6.1 on 2026-10-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_attendance_break_seconds_attendance_break_started_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='location_mode',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('remote', 'Remote / Work from Home')], max_length=20),
        ),
    ]
