# Generated by Django 6.1.1 on 2026-10-02 07:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_project_category_project_goals_project_objective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('processing', 'Processing')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('formula', models.TextField(blank=True)),
                ('dates', models.JSONField(blank=True, default=list)),
                ('remarks', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.salary')),
            ],
            options={
                'ordering': ['component_type', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollTaxDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=9)),
                ('document_type', models.CharField(choices=[('form16_a', 'Form 16 Part A'), ('form16_b', 'Form 16 Part B'), ('tax_computation', 'Annual Tax Computation'), ('investment_declaration', 'Investment Declaration Summary')], max_length=30)),
                ('file', models.FileField(upload_to='payroll_tax_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_tax_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-financial_year', 'document_type'],
                'unique_together': {('employee', 'financial_year', 'document_type')},
            },
        ),
    ]
