# Generated by Django 6.1.1 on 2026-10-03 08:38

from django.db import migrations, models
from django.db.models import Q


def populate_employee_ids(apps, schema_editor):
    User = apps.get_model('core', 'User')
    for employee in User.objects.filter(role='employee').filter(
        Q(employee_id__isnull=True) | Q(employee_id='')
    ).order_by('pk'):
        User.objects.filter(pk=employee.pk).update(
            employee_id=f'EMP{employee.pk:06d}'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_salary_remarks_alter_salary_status_salarycomponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('resigned', 'Resigned'), ('terminated', 'Terminated')], default='active', max_length=20),
        ),
        migrations.RunPython(populate_employee_ids, migrations.RunPython.noop),
    ]
