# Generated by Django 6.1.1 on 2026-10-03 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_existing_document_activity(apps, schema_editor):
    EmployeeActivity = apps.get_model('core', 'EmployeeActivity')
    EmployeeDocument = apps.get_model('core', 'EmployeeDocument')
    for document in EmployeeDocument.objects.all().iterator():
        activity = EmployeeActivity.objects.create(
            employee_id=document.employee_id,
            activity_type='document_uploaded',
            description=f'{document.title} · {document.category}',
        )
        EmployeeActivity.objects.filter(pk=activity.pk).update(
            created_at=document.uploaded_at
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_employee_id_user_employment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Employee created'), ('updated', 'Profile updated'), ('status_changed', 'Employment status changed'), ('deactivated', 'Account deactivated'), ('reactivated', 'Account reactivated'), ('document_uploaded', 'Document uploaded'), ('document_deleted', 'Document deleted')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_management_actions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.RunPython(populate_existing_document_activity, migrations.RunPython.noop),
    ]
