# Generated by Django 6.1.1 on 2026-10-03 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_leave_policies(apps, schema_editor):
    LeavePolicy = apps.get_model('core', 'LeavePolicy')
    leave_types = ['Sick', 'Casual', 'Paid', 'Earned', 'Unpaid', 'Maternity', 'Paternity']
    for leave_type in leave_types:
        LeavePolicy.objects.get_or_create(
            leave_type=leave_type,
            defaults={
                'annual_quota': None,
                'is_paid': leave_type != 'Unpaid',
                'requires_document': leave_type in {'Sick', 'Maternity', 'Paternity'},
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_employeeactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Sick', 'Sick'), ('Casual', 'Casual'), ('Paid', 'Paid'), ('Earned', 'Earned'), ('Unpaid', 'Unpaid'), ('Maternity', 'Maternity'), ('Paternity', 'Paternity')], max_length=20, unique=True)),
                ('annual_quota', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_document', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['leave_type'],
            },
        ),
        migrations.AddField(
            model_name='attendancecorrectionrequest',
            name='approval_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendancecorrectionrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancecorrectionrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attendance_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('Sick', 'Sick'), ('Casual', 'Casual'), ('Paid', 'Paid'), ('Earned', 'Earned'), ('Unpaid', 'Unpaid'), ('Maternity', 'Maternity'), ('Paternity', 'Paternity')], default='Casual', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.RunPython(create_default_leave_policies, migrations.RunPython.noop),
    ]
