# Generated by Django 6.1.1 on 2026-10-03 11:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_organization_and_salary_data(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Department = apps.get_model('core', 'Department')
    Designation = apps.get_model('core', 'Designation')
    SalaryStructure = apps.get_model('core', 'SalaryStructure')
    SalaryRevision = apps.get_model('core', 'SalaryRevision')
    database = schema_editor.connection.alias

    for employee in User.objects.using(database).filter(role='employee'):
        department_name = (employee.department or '').strip()
        designation_name = (employee.designation or '').strip()
        if department_name or designation_name:
            if not department_name:
                department_name = 'General'
                employee.department = department_name
            department, _ = Department.objects.using(database).get_or_create(
                name=department_name,
            )
            employee.department_record_id = department.pk
            if designation_name:
                designation, _ = Designation.objects.using(database).get_or_create(
                    department=department,
                    name=designation_name,
                )
                employee.designation_record_id = designation.pk
            employee.save(
                using=database,
                update_fields=[
                    'department',
                    'department_record',
                    'designation_record',
                ],
            )

        if employee.salary_amount and employee.salary_amount > 0:
            effective_from = employee.joining_date or django.utils.timezone.localdate()
            structure = SalaryStructure.objects.using(database).create(
                employee_id=employee.pk,
                basic_salary=employee.salary_amount,
                effective_from=effective_from,
            )
            SalaryRevision.objects.using(database).create(
                structure_id=structure.pk,
                basic_salary=employee.salary_amount,
                hra=0,
                allowances=0,
                deductions=0,
                attendance_based=True,
                effective_from=effective_from,
                reason='Migrated from legacy monthly salary amount',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_leavepolicy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salary',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('processing', 'Processing'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
                ('parent_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_departments', to='core.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.department'),
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designations', to='core.department')),
            ],
            options={
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='designation_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.designation'),
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('attendance_based', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('attendance_based', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_revisions_made', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.salarystructure')),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='designation',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='unique_designation_per_department'),
        ),
        migrations.RunPython(migrate_organization_and_salary_data, migrations.RunPython.noop),
    ]
