# Generated by Django 6.1.1 on 2026-10-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_salary_amount_alter_salary_status_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarycomponent',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
