from django.urls import path
from .views_api import EmployeeListAPIView
from .views import (
    EmployeeDashboardView,
    EmployeeCheckInView,
    EmployeeCheckOutView,
    EmployeeAttendanceBreakView,
    EmployeeAttendanceCorrectionView,
    EmployeeAttendanceExportView,
    EmployeeAttendanceView,
    EmployeeWorkLogsView,
    EmployeeWorkLogExportView,
    AdminWorkLogExportView,
    EmployeeAddWorkLogView,
    EmployeeDeleteWorkLogView,
    EmployeeEditWorkLogView,
    EmployeeLeavesView,
    EmployeeApplyLeaveView,
    EmployeeWithdrawLeaveView,
    EmployeeLeaveDocumentView,
    EmployeeProfileView,
    EmployeeProfilePhotoView,
    EmployeeDocumentDownloadView,
    EmployeePasswordChangeView,
    EmployeeSalaryView,
    EmployeePayslipDownloadView,
    EmployeePayrollTaxDocumentView,
    EmployeeCalendarView,
    EmployeeProjectsView,
)

urlpatterns = [
    # APIs
    path('employees/', EmployeeListAPIView.as_view(), name='api_employee_list'),
    
    # Employee Views
    path('dashboard/', EmployeeDashboardView.as_view(), name='employee_dashboard'),
    path('check-in/', EmployeeCheckInView.as_view(), name='employee_check_in'),
    path('check-out/', EmployeeCheckOutView.as_view(), name='employee_check_out'),
    path('attendance/break/', EmployeeAttendanceBreakView.as_view(), name='employee_attendance_break'),
    path('attendance/correction/', EmployeeAttendanceCorrectionView.as_view(), name='employee_attendance_correction'),
    path('attendance/export/', EmployeeAttendanceExportView.as_view(), name='employee_attendance_export'),
    path('attendance/', EmployeeAttendanceView.as_view(), name='employee_attendance'),
    path('work-logs/', EmployeeWorkLogsView.as_view(), name='employee_work_logs'),
    path('work-logs/export/', EmployeeWorkLogExportView.as_view(), name='employee_work_logs_export'),
    path('work-logs/add/', EmployeeAddWorkLogView.as_view(), name='employee_add_worklog'),
    path('work-logs/delete/<int:pk>/', EmployeeDeleteWorkLogView.as_view(), name='employee_delete_worklog'),
    path('work-logs/edit/<int:pk>/', EmployeeEditWorkLogView.as_view(), name='employee_edit_worklog'),
    path('admin/employees/<int:employee_id>/work-logs/export/', AdminWorkLogExportView.as_view(), name='admin_employee_work_logs_export'),
    path('leaves/', EmployeeLeavesView.as_view(), name='employee_leaves'),
    path('leaves/apply/', EmployeeApplyLeaveView.as_view(), name='employee_apply_leave'),
    path('leaves/<int:pk>/withdraw/', EmployeeWithdrawLeaveView.as_view(), name='employee_withdraw_leave'),
    path('leaves/<int:pk>/document/', EmployeeLeaveDocumentView.as_view(), name='employee_leave_document'),
    path('profile/', EmployeeProfileView.as_view(), name='employee_profile'),
    path('profile/photo/', EmployeeProfilePhotoView.as_view(), name='employee_profile_photo'),
    path('profile/photo/<int:user_id>/', EmployeeProfilePhotoView.as_view(), name='employee_photo_by_id'),
    path('profile/password/', EmployeePasswordChangeView.as_view(), name='employee_password_change'),
    path('profile/documents/<int:pk>/download/', EmployeeDocumentDownloadView.as_view(), name='employee_document_download'),
    path('salary/', EmployeeSalaryView.as_view(), name='employee_salary'),
    path('salary/payslip/<int:pk>/', EmployeePayslipDownloadView.as_view(), name='employee_payslip_download'),
    path('salary/tax-documents/<int:pk>/', EmployeePayrollTaxDocumentView.as_view(), name='employee_tax_document_download'),
    path('calendar/', EmployeeCalendarView.as_view(), name='employee_calendar'),
    path('projects/', EmployeeProjectsView.as_view(), name='employee_projects'),
]

